name: Deploy Pterodactyl Panel and Wings on GitHub Codespaces

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Deploy Containers
      run: |
        docker-compose pull  # Tarik image terbaru
        docker-compose up -d  # Jalankan seluruh service
    - name: Clean up dangling images
      run: docker image prune -af
