version: '3.8'

services:
  # Pterodactyl Panel
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl_panel
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=pterodactyl
      - DB_USERNAME=pterodactyl
      - DB_PASSWORD=your_password
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./panel_data:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - database
      - redis
    networks:
      - pterodactyl_network

  # Pterodactyl Wings
  wings:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl_wings
    environment:
      - WINGS_CONFIG="/etc/pterodactyl/config.yml"
    volumes:
      - ./wings_config.yml:/etc/pterodactyl/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./wings_data:/var/lib/pterodactyl
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - pterodactyl_network

  # MySQL/MariaDB Database
  database:
    image: mysql:5.7
    container_name: pterodactyl_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pterodactyl
      MYSQL_USER: pterodactyl
      MYSQL_PASSWORD: your_password
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - pterodactyl_network

  # Redis (cache & session)
  redis:
    image: redis:alpine
    container_name: pterodactyl_redis
    volumes:
      - ./redis_data:/data
    networks:
      - pterodactyl_network

networks:
  pterodactyl_network:
    driver: bridge
