# Wings Configuration for Pterodactyl
uuid: your-node-uuid  # UUID dari Node Pterodactyl
token: your-node-secret  # Token Secret dari Panel
api:
  host: 0.0.0.0
  port: 8080
system:
  data: /var/lib/pterodactyl
  sftp:
    bind_address: 0.0.0.0
    port: 2022
docker:
  container:
    user: 1000
  network:
    name: pterodactyl0
    mode: bridge
  storage:
    driver: overlay2
  enable_ipv6: true
  ipc_mode: none
  pid_mode: none
